# `NumPy`
### [numpy.org](https://numpy.org/)
<sub>(https://people.unica.it/giulianoarmano/files/2013/06/numpy.pdf  
https://www.math.unipd.it/~aiolli/corsi/1819/aa/PyA8--python_scientific.pdf  
https://stackoverflow.com/questions/tagged/numpy )</sub>



Numpy rappresenta un po' la _"core library"_ per il calcolo scientifico in Python. Fornisce oggetti computazionali ad alte prestazioni per vettori e matrici multidimensionali e tutti gli strumenti necessari per lavorare con questi:  

- funzioni matematiche di alto livello con cui operare(algebra lineare, trasformate di Fourier, etc.)
- array multidimensionali
- funzioni per numeri casuali

Se si ha un po' di confidenza con MATLAB, [qui](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) potete trovare una comparazione utile per iniziare poi ad usare Numpy.

Per usare Numpy, dobbiamo innanzitutto importare il modulo **`numpy`**:

```import numpy as np```

In [1]:
import numpy as np

### Array

L'oggetto più importate del pacchetto è l'_array_.  
Un _array_ `numpy` è:

- un vettore di valori **tutti dello stesso tipo**. (principale differenza con le liste). Il tipo è generalmente un `int` o `float`
- è caratterizzato da un **_rank_** e da una **_shape_**
 - il **rank** indica il numero di dimensioni dell'array
 - la **shape** è una tupla che indica la lunghezza lungo la singola dimensione.
- risulta molto efficiente sulle grandi dimensioni.

Si può inizializzare un _array_ con il metodo costruttore **`array()`** e poi accedere agli elementi usando le parentesi quadre:

In [2]:
a = np.array([1, 2, 3])  # Crea un array ad 1 dimensione(rank)
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Cambio l'elemento di indice 0 dell'array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # rank 2 array: 2 righe 3 colonne
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Il metodo `.array()` prende 2 argomenti:

- una lista contentente i valori
- la specifica del tipo di dato(argomento opzionale)

La manipolazione degli array è identica a quella già vista per le liste:

In [5]:
print(b[:1]) # slicing tutto il contenuto della prima riga
print(b[1,1]) # accesso al singolo elemento
b[1,2] = 10 # modifica
print(b[1,2])
print(b[:])

[[1 2 3]]
5
10
[[ 1  2  3]
 [ 4  5 10]]


#### SLICING

Poichè gli array possono essere multidimensionali, nello _slicing_ bisogna specificare una 'slice'(fetta)per ogni dimensione dell'array. 

**FACCIAMO UN PO' DI CHIAREZZA** e partiamo creando questo:  
![slicing1](img/slicing_0.png)

**Creo due array di rank 1 con shape (6)**  

` [0, 1, 2, 3, 4, 5]
 [0, 10, 20, 30, 40, 50]`

In [6]:
import numpy as np

x = np.array([0,1,2,3,4,5])
print(x)
y = np.array([0,10,20,30,40,50])
print(y)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]


**quindi inizializzo un array di rank 2 con shape 6 per entrambe le dimensioni**

In [7]:
new =np.zeros([6,6], int) 

print(new)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


**ora riempio l'array con i valori** (dopo vedremo come semplificare la somma con le funzioni standard)

In [8]:
for i in range(len(x)): 
    ...:     for j in range(len(y)): 
    ...:         new[j,i] = y[j] + x[i]
print(new)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


Vediamo degli esempi di **_slicing_**(ricordiamoci sempre che l'indice finale è escluso)

`>>>new[0,3:5]`  
`array([3, 4])`
![slicing1](img/slicing_1.png)

***

`>>>new[0,3:5]`  
`array([3, 4])`
![slicing2](img/slicing_2.png)
`>>>new[4:,4:]`  
`array([44,45],[54,55])`

***

`>>>new[0,3:5]
array([3, 4])`  
`>>>new[4:,4:]
array([44,45],[54,55])`
![slicing3](img/slicing_3.png)  
`>>>new[:,2]
array([ 2, 12, 22, 32, 42, 52])`  


***

`>>>new[0,3:5]`  
`array([3, 4])`  
`>>>new[4:,4:]`  
`array([44,45],[54,55])`  
`>>>new[:,2]`  
`array([ 2, 12, 22, 32, 42, 52])`
![slicing4](img/slicing_4.png)
`>>>new[2::2,::2]`  
`array([[20, 22, 24],
       [40, 42, 44]])`

in questo ultimo esempio la sintassi è: `[start_pos::step]`  
`[start:end:step]`

Lo _slicing_ crea dei riferimenti all'array originale:

In [9]:
rif_a_new = new[:,2]
print(rif_a_new)

[ 2 12 22 32 42 52]


Se modifichiamo l'array `rif_a_new` modifichiamo anche l'array `new`:

In [10]:
rif_a_new[0] = 62
print('Questo è il riferimento: ', rif_a_new, '\n')
print(new)

Questo è il riferimento:  [62 12 22 32 42 52] 

[[ 0  1 62  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


E' possibile mixare l'indirizzamento agli elementi con indici interi e _slicing_. Però attenzione che così facendo si otterrà un array di _rank_ inferiore all'array originale:

In [11]:
# Crea rank 2 array con shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Di seguito 2 modi per indirizzare la riga di mezzo.

- indici interi e slice produce un array di rank inferiore;
- con solo slice si mantiene lo stesso rank dell'array originale

In [12]:
row_r1 = a[1, :]    # Rank 1 seconda riga di a  
row_r2 = a[1:2, :]  # Rank 2 seconda riga di a
row_r3 = a[[1], :]  # Rank 2 seconda riga di a
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [13]:
# Possiamo usare la stesse tecniche per le colonne di un array:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


***

#### Numpy fornisce diverse funzioni per inizializzare array:

In [14]:
a = np.zeros((2,2))  # Crea un array di tutti zeri
print(a)

[[0. 0.]
 [0. 0.]]


In [15]:
b = np.ones((1,2))   # Crea un array di tutti uno
print(b)

[[1. 1.]]


In [16]:
c = np.full((2,2), 7) # Crea un array con una costante
print(c) 

[[7 7]
 [7 7]]


In [17]:
d1 = np.identity(4) # Crea una matrice identità
print(d1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
d = np.eye(6, k=2) # Crea una matrice identità 2x2 sulla diagonale k-ma
print(d)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
e = np.random.random((2,2)) # Crea un array riempito con valori random
print(e)

[[0.8664505  0.55241203]
 [0.25074755 0.33975131]]


oppure si può inizializzare un array con il metodo **`range()`** o con il metodo **`arange()`**:

In [20]:
a = np.array(range(6), float).reshape((2,3))
b = np.arange(5, dtype=float) #dtype crea un oggetto 'data type'
print(a)
print(b)

[[0. 1. 2.]
 [3. 4. 5.]]
[0. 1. 2. 3. 4.]


Qui sopra abbiamo anche usato il metodo **`reshape()`** per modificare le dimensione dell'array `a`

### Proprietà degli array

- `shape` abbiamo visto ritorna la tupla con le dimensioni dell'array
- `dtype` ritorna il tipo di dato memorizzato nell'array

In [21]:
a.dtype

dtype('float64')

## Copia di array
Se serve si può anche copiare un array tramite il metodo **`copy()`**

In [22]:
a = np.array([1, 2, 3], float)
b = a # b è una variabile che punta allo stesso dato
c = a.copy() # metodo copy() crea un nuovo array
a[0] = 0
print(a)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


Gli elementi di un array sono **ordinabili** con il metodo **`sort()`**

In [23]:
a = np.array([6, 2, 5, -1, 0], float)
a.sort()
print(a)

[-1.  0.  2.  5.  6.]


Con il metodo **`clip()`** posso filtrare gli elementi esterni ad un certo intervallo dell'array:

In [24]:
a = np.array([0, 1, 2, -1, 5, 6, 3], float)
a.clip(2,6)

array([2., 2., 2., 2., 5., 6., 3.])

## Conversione
Un Numpy array può all'occorenza essere trasformato in una lista con il metodo **`tolist()`**

In [25]:
a = np.array([1, 2, 3], float)
a.tolist()
# oppure con il casting 
#list(a)

[1.0, 2.0, 3.0]

Conversione **da/in** formato stringa con i metodi **`tostring()`** e **`fromstring`**

In [26]:
a = np.array([1, 2, 3], float)
s = a.tostring()
print(s) # produce una stringa di bytes

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


## Generazione di matrice trasposta

Si usa il metodo **`transpose()`** per trasporre un array multidimensionale

In [27]:
a = np.array([[0., 1., 2.], [3., 4., 5.]], dtype=float)
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [28]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

## Trasformazione da n-D a 1-D

Si può rendere monodimensionale un array a più dimensioni con il metodo **`flatten()`**

In [29]:
piatto = a.flatten()
print(piatto)

[0. 1. 2. 3. 4. 5.]


## Aritmetica di base sugli Array

Le operazioni di somma, sottrazione, moltiplicazione, divisione, elevamento a potenza, sono definibili sia con gli operatori relativi che con le funzioni del modulo numpy:

**Gli operatori aritmetici vengono applicati elemento per elemento.**

**SOMMA**

In [30]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
print('\n')
#SOMMA
print(x + y)  # somma con operatore
print(np.add(x, y)) #somma con funzione

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


**SOTTRAZIONE**

In [31]:
# SOTTRAZIONE
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


**PRODOTTO**

In [32]:
# PRODOTTO
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


**DIVISIONE**

In [33]:
# DIVISIONE
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**RADICE QUADRATA**

In [34]:
# RADICE QUADRATA
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Notare che a differenza di MATLAB, `*` moltiplica il singolo elemento, non è una moltiplicazione matriciale! Per quest'ultima dovremo usare il tipo di dato `matrix`(però in parte deprecato a favore del metodo seguente).  
Per effettuare **prodotto scalare o vettoriale** bisogna usare la funzione **`dot()`**:

In [35]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# prodotto vettoriale; produce 219
print(v.dot(w)) # dot() metodo di istanza 
print(np.dot(v, w)) # dot funzione del modulo np 

219
219


In [36]:
# Prodotto Matrice vettore; produce rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [37]:
# Prodotto matrice matrice; produce rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy fornisce molte funzioni standard per operare sugli array:  
`abs()`, `sign()`, `sqrt()`, `log()`, `log10()`, `exp()`, `sin()`,
`cos()`, `tan()`, `arcsin()`, `arccos()`, `arctan()`, `sinh()`,
`cosh()`, `tanh()`, `arcsinh()`, `arccosh()`, `arctanh()`

**Arrotondamento verso il valore più piccolo**:
`floor()`

In [38]:
a = np.array([1.1, 1.5, 1.9], float)
print(np.floor(a))
#array([ 1., 1., 1.])

[1. 1. 1.]


**Arrotondamento verso il valore più grande**:
`ceil()`

**Arrotondamento verso il valore più vicino**:  
`rint()`

In [39]:
print(np.rint(a))

[1. 2. 2.]


Una delle funzioni più usate è certamente la **`sum()`**

In [40]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Calcola la somma di tutti gli elementi; prints "10"
print(np.sum(x, axis=0))  # Calcola la somma per ogni colonna; prints "[4 6]"
print(np.sum(x, axis=1))  # Calcola la somma per ogni riga; prints "[3 7]"

10
[4 6]
[3 7]


ma esistono anche la **`prod()`**, **`mean()`**, **`var()`**, **`std()`**, **`min()`**, **`max()`** ...

In [41]:
print(x.mean())
print(x.min())
print(x.max())

2.5
1
4


Per una lista completa di tutte le funzioni matematiche disponibili in numpy si può consultare la [documentazione](https://numpy.org/doc/stable/reference/index.html).

Oltre alle funzioni e operazioni matematiche sugli array, spesso abbiamo bisogno anche di ridimensionare o manipolare i dati negli array. L'esempio più semplice è quello di trasporre una matrice che come abbiamo già visto si può fare con la funzione`transpose()`, ma ancora più semplice è usando l'attributo **`T`** degli oggetti array:

In [42]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [43]:
v = np.array([[1,2,3]])
print(v) 
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


***

## Operatori di confronto
- Gli operatori booleani di confronto sono definiti sugli array di uguale dimensione
- Il risultato del confronto è un array di valori booleani

In [44]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
print(a > b)

[ True False False]


In [45]:
print(a == b)

[False  True False]


In [46]:
print(a > 2)

[False  True False]


Ulteriori operatori di confronto si possono approfondire nella [documentazione](https://docs.scipy.org/doc/numpy/reference/routines.logic.html)

## Broadcasting

Broadcasting è un potente meccanismo che consente di operare su array con diverse dimensioni. Spesso capita di avere un array più piccolo ed uno più grande tra i quali effetture delle operazioni.
  
Se possibile tutti gli array vengono convertiti in elementi aventi la stessa dimensione.

Per esempio supponiamo di voler aggiungere un vettore costante per ogni riga di una data matrice:

In [47]:
# Aggiungo il vettore v ad ogni riga della matrice x,
# memorizzo il risultato nella matrice y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #4 righe 3 colonne
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Crea una matrice vuota con la stessa lunghezza di x

# Aggiungo il vettore v
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


FIn qui nessun problema, ma se la matrice fosse molto grande, allora il _loop_ in Python diventerebbe molto pesante e lento. 
Notare che aggiungere il vettore `v` ad ogni riga di `x` equivale a creare una nuova matrice `vv` con incolonnate verticalmente più copie di `v`; quindi effettuando un somma elemento per elemento tra `x` e `vv`:

In [48]:
vv = np.tile(v, (4, 1))  # incollonno 4 copie di v
print(vv)                 # Print "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [49]:
y = x + vv  # Sommo x e vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy _broadcasting_ consente di effettuare questa operazione senza creare le copie multiple di `v` come nell'esempio sopra:

In [50]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


La linea `y = x + v` funziona anche con `x` di shape `(4, 3)` e `v` con shape `(3,)` grazie al broadcasting; questa funziona come se effettivamente `v` avesse shape `(4, 3)`, dove ogni riga fosse una copia di `v`, e la somma fosse fatta elemento per elemento.

**Il broadcasting è possibile se il numero di colonne del
primo è uguale al numero di righe del secondo,
altrimenti l'interprete Python restituisce l'eccezione**
`“ValueError: frames are not aligned”`

Le funzioni che supportano il broadcasting sono conosciute come _universal functions_ `ufunc`. Più informazioni nella [documentazione](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs).

Di seguito alcune altre applicazioni del broadcasting:

In [ ]:
# Calcolo prodotto esterno di vettori
v = np.array([1,2,3])  # v shape (3,)
w = np.array([4,5])    # w shape (2,)
# Per calcolare il prodotto esterno, dobbiamo prima ridimensionare v per essere un vettore di
# colonna di shape (3, 1); quindi possiamo fare il broadcast di questo con w per produrre
# un output di shape (3, 2), che sarà il prodotto esterno di v e w:

print(np.reshape(v, (3, 1)) * w)

In [52]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
x = np.ones(shape=(2,3)) 
w = np.random.randint(100, size=(2,))

print((x.T + w).T)

[[88. 88. 88.]
 [11. 11. 11.]]


In [53]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[88. 88. 88.]
 [11. 11. 11.]]


In [54]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[2. 2. 2.]
 [2. 2. 2.]]


Possiamo dire che il **Broadcasting** in genere rende il codice più coinciso e veloce.

***

## Algebra lineare: il pacchetto linalg
Il sotto-pacchetto **`np.linalg`** fornisce gli strumenti di base per l'algebra lineare, basandosi su BLAS e LAPACK fornisce implementazioni di basso livello degli algoritmi di algebra lineare.  

- Abbiamo il metodo **`det()`** per calcolare il determinante di una matrice;
- La funzione **`eig()`** ritorna una tupla con gli autovalori e gli autovettori della matrice;
- La funzione **`inv()`** ritorna l'inversa di una matrice
- e molti altri...

Per dettagli ed esempi vi rimando alla [documentazione](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

***

## Calcolo Polinomiale

Numpy fornisce un modulo per calcoli polinomiali, contentente diverse funzioni per lavorare appunto con i polinomi. Di seguito ne elenco solo alcuni:

- Il metodo **`polyint()`** accetta un array contenente i coefficienti di un polinomio e ritorna un array con i coefficienti del polinomio integrato [documentazione](https://numpy.org/doc/stable/reference/generated/numpy.polyint.html#numpy.polyint)
- Il metodo **`polyder()`** accetta un array contenente i coefficienti del polinomio e ritorna un array con i coefficienti del polinomio derivato [documentazione](https://numpy.org/doc/stable/reference/generated/numpy.polyder.html#numpy.polyder)

Sono disponibili tutte le funzioni di somma, sottrazione, moltiplicazione, divisione fra polinomi:

- **`polyadd()`**, **`polysub()`**, **`polymul()`**, **`polydiv()`**

La lista completa di tutte le funzione del pacchetto `Polinomial` si trova nella [documentazione](https://numpy.org/doc/stable/reference/routines.polynomials.html)

***

## Generazione di numeri casuali
Il sotto-pacchetto **`np.random`** mette a disposizione strumenti per la generazione di numeri casuali con seme arbitrario

- **`np.random.seed()`** Imposta il seme. 
- Generazione di un singolo numero casuale uniforme compreso fra 0.0 e 1.0 con la funzione **`np.random.random()`**
- Generazione di un singolo numero casuale intero uniforme in un intervallo (a, b) con la funzione **` np.random.randint(x, y)`** dove _x_ e _y_ sono 2 numeri interi

In [55]:
np.random.seed(3765) #il seme può essere un qualsiasi numero intero
a = np.random.random()
print(f'a: {a} è un numero casuale nell\'intervallo 0.0 e 1.0')
b = np.random.randint(1,20)
print(f'b: {b} è un numero casuale nell\'intervallo 1 - 20')

a: 0.5837379036003874 è un numero casuale nell'intervallo 0.0 e 1.0
b: 5 è un numero casuale nell'intervallo 1 - 20


Con il pacchetto **`numpy.random`** è possibile produrre sequenze per tutte le principali distribuzioni statistiche:

- **`np.random.poisson()`**
- **`np.random.normal()`** (distribuzione Gaussiana)

Per un approfondimento di tutte le routine fornite rimando alla _solita_ [documentazione ufficiale](https://numpy.org/doc/stable/reference/random/index.html)